function serviceHeader(){return new ServiceHeader(30,"Papago","Naver Papago is a multilingual machine translation cloud service provided by Naver Corporation."+Const.NL2+serviceHost()+Const.NL2+"\u00a9 NAVER Corp.",Capability.TRANSLATE|Capability.DETECT_LANGUAGE)}function serviceHost(b,k,a){return"https://papago.naver.com"}function serviceLink(b,k,a){var l=serviceHost();b&&(l+=format("/?sk={0}&tk={1}&st={2}",codeFromLanguage(k),codeFromLanguage(a),encodeGetParam(b)));return l}
var CryptoJS=CryptoJS||function(b,k){var a={},l=a.lib={},m=function(){},p=l.Base={extend:function(d){m.prototype=this;var n=new m;d&&n.mixIn(d);n.hasOwnProperty("init")||(n.init=function(){n.$super.init.apply(this,arguments)});n.init.prototype=n;n.$super=this;return n},create:function(){var d=this.extend();d.init.apply(d,arguments);return d},init:function(){},mixIn:function(d){for(var n in d)d.hasOwnProperty(n)&&(this[n]=d[n]);d.hasOwnProperty("toString")&&(this.toString=d.toString)},clone:function(){return this.init.prototype.extend(this)}},
r=l.WordArray=p.extend({init:function(d,n){d=this.words=d||[];this.sigBytes=n!=k?n:4*d.length},toString:function(d){return(d||u).stringify(this)},concat:function(d){var n=this.words,c=d.words,b=this.sigBytes;d=d.sigBytes;this.clamp();if(b%4)for(var a=0;a<d;a++)n[b+a>>>2]|=(c[a>>>2]>>>24-a%4*8&255)<<24-(b+a)%4*8;else if(65535<c.length)for(a=0;a<d;a+=4)n[b+a>>>2]=c[a>>>2];else n.push.apply(n,c);this.sigBytes+=d;return this},clamp:function(){var d=this.words,n=this.sigBytes;d[n>>>2]&=4294967295<<32-
n%4*8;d.length=b.ceil(n/4)},clone:function(){var d=p.clone.call(this);d.words=this.words.slice(0);return d},random:function(d){for(var n=[],c=0;c<d;c+=4)n.push(4294967296*b.random()|0);return new r.init(n,d)}}),v=a.enc={},u=v.Hex={stringify:function(d){var c=d.words;d=d.sigBytes;for(var a=[],b=0;b<d;b++){var l=c[b>>>2]>>>24-b%4*8&255;a.push((l>>>4).toString(16));a.push((l&15).toString(16))}return a.join("")},parse:function(d){for(var c=d.length,a=[],b=0;b<c;b+=2)a[b>>>3]|=parseInt(d.substr(b,2),16)<<
24-b%8*4;return new r.init(a,c/2)}},c=v.Latin1={stringify:function(d){var c=d.words;d=d.sigBytes;for(var b=[],a=0;a<d;a++)b.push(String.fromCharCode(c[a>>>2]>>>24-a%4*8&255));return b.join("")},parse:function(d){for(var c=d.length,b=[],a=0;a<c;a++)b[a>>>2]|=(d.charCodeAt(a)&255)<<24-a%4*8;return new r.init(b,c)}},t=v.Utf8={stringify:function(d){try{return decodeURIComponent(escape(c.stringify(d)))}catch(a){throw Error("Malformed UTF-8 data");}},parse:function(d){return c.parse(unescape(encodeURIComponent(d)))}},
w=l.BufferedBlockAlgorithm=p.extend({reset:function(){this._data=new r.init;this._nDataBytes=0},_append:function(d){"string"==typeof d&&(d=t.parse(d));this._data.concat(d);this._nDataBytes+=d.sigBytes},_process:function(d){var a=this._data,c=a.words,l=a.sigBytes,k=this.blockSize,w=l/(4*k),w=d?b.ceil(w):b.max((w|0)-this._minBufferSize,0);d=w*k;l=b.min(4*d,l);if(d){for(var q=0;q<d;q+=k)this._doProcessBlock(c,q);q=c.splice(0,d);a.sigBytes-=l}return new r.init(q,l)},clone:function(){var d=p.clone.call(this);
d._data=this._data.clone();return d},_minBufferSize:0});l.Hasher=w.extend({cfg:p.extend(),init:function(d){this.cfg=this.cfg.extend(d);this.reset()},reset:function(){w.reset.call(this);this._doReset()},update:function(d){this._append(d);this._process();return this},finalize:function(d){d&&this._append(d);return this._doFinalize()},blockSize:16,_createHelper:function(d){return function(a,c){return(new d.init(c)).finalize(a)}},_createHmacHelper:function(d){return function(a,c){return(new q.HMAC.init(d,
c)).finalize(a)}}});var q=a.algo={};return a}(Math);
(function(b){function k(a,c,d,b,l,k,m){a=a+(c&d|~c&b)+l+m;return(a<<k|a>>>32-k)+c}function a(a,c,d,b,l,k,m){a=a+(c&b|d&~b)+l+m;return(a<<k|a>>>32-k)+c}function l(a,c,d,b,l,k,m){a=a+(c^d^b)+l+m;return(a<<k|a>>>32-k)+c}function m(a,c,d,b,l,k,m){a=a+(d^(c|~b))+l+m;return(a<<k|a>>>32-k)+c}for(var p=CryptoJS,r=p.lib,v=r.WordArray,u=r.Hasher,r=p.algo,c=[],t=0;64>t;t++)c[t]=4294967296*b.abs(b.sin(t+1))|0;r=r.MD5=u.extend({_doReset:function(){this._hash=new v.init([1732584193,4023233417,2562383102,271733878])},
_doProcessBlock:function(b,q){for(var d=0;16>d;d++){var n=q+d,p=b[n];b[n]=(p<<8|p>>>24)&16711935|(p<<24|p>>>8)&4278255360}var d=this._hash.words,n=b[q+0],p=b[q+1],r=b[q+2],t=b[q+3],u=b[q+4],v=b[q+5],x=b[q+6],y=b[q+7],z=b[q+8],A=b[q+9],B=b[q+10],C=b[q+11],D=b[q+12],E=b[q+13],F=b[q+14],G=b[q+15],e=d[0],f=d[1],g=d[2],h=d[3],e=k(e,f,g,h,n,7,c[0]),h=k(h,e,f,g,p,12,c[1]),g=k(g,h,e,f,r,17,c[2]),f=k(f,g,h,e,t,22,c[3]),e=k(e,f,g,h,u,7,c[4]),h=k(h,e,f,g,v,12,c[5]),g=k(g,h,e,f,x,17,c[6]),f=k(f,g,h,e,y,22,c[7]),
e=k(e,f,g,h,z,7,c[8]),h=k(h,e,f,g,A,12,c[9]),g=k(g,h,e,f,B,17,c[10]),f=k(f,g,h,e,C,22,c[11]),e=k(e,f,g,h,D,7,c[12]),h=k(h,e,f,g,E,12,c[13]),g=k(g,h,e,f,F,17,c[14]),f=k(f,g,h,e,G,22,c[15]),e=a(e,f,g,h,p,5,c[16]),h=a(h,e,f,g,x,9,c[17]),g=a(g,h,e,f,C,14,c[18]),f=a(f,g,h,e,n,20,c[19]),e=a(e,f,g,h,v,5,c[20]),h=a(h,e,f,g,B,9,c[21]),g=a(g,h,e,f,G,14,c[22]),f=a(f,g,h,e,u,20,c[23]),e=a(e,f,g,h,A,5,c[24]),h=a(h,e,f,g,F,9,c[25]),g=a(g,h,e,f,t,14,c[26]),f=a(f,g,h,e,z,20,c[27]),e=a(e,f,g,h,E,5,c[28]),h=a(h,e,
f,g,r,9,c[29]),g=a(g,h,e,f,y,14,c[30]),f=a(f,g,h,e,D,20,c[31]),e=l(e,f,g,h,v,4,c[32]),h=l(h,e,f,g,z,11,c[33]),g=l(g,h,e,f,C,16,c[34]),f=l(f,g,h,e,F,23,c[35]),e=l(e,f,g,h,p,4,c[36]),h=l(h,e,f,g,u,11,c[37]),g=l(g,h,e,f,y,16,c[38]),f=l(f,g,h,e,B,23,c[39]),e=l(e,f,g,h,E,4,c[40]),h=l(h,e,f,g,n,11,c[41]),g=l(g,h,e,f,t,16,c[42]),f=l(f,g,h,e,x,23,c[43]),e=l(e,f,g,h,A,4,c[44]),h=l(h,e,f,g,D,11,c[45]),g=l(g,h,e,f,G,16,c[46]),f=l(f,g,h,e,r,23,c[47]),e=m(e,f,g,h,n,6,c[48]),h=m(h,e,f,g,y,10,c[49]),g=m(g,h,e,f,
F,15,c[50]),f=m(f,g,h,e,v,21,c[51]),e=m(e,f,g,h,D,6,c[52]),h=m(h,e,f,g,t,10,c[53]),g=m(g,h,e,f,B,15,c[54]),f=m(f,g,h,e,p,21,c[55]),e=m(e,f,g,h,z,6,c[56]),h=m(h,e,f,g,G,10,c[57]),g=m(g,h,e,f,x,15,c[58]),f=m(f,g,h,e,E,21,c[59]),e=m(e,f,g,h,u,6,c[60]),h=m(h,e,f,g,C,10,c[61]),g=m(g,h,e,f,r,15,c[62]),f=m(f,g,h,e,A,21,c[63]);d[0]=d[0]+e|0;d[1]=d[1]+f|0;d[2]=d[2]+g|0;d[3]=d[3]+h|0},_doFinalize:function(){var a=this._data,c=a.words,d=8*this._nDataBytes,l=8*a.sigBytes;c[l>>>5]|=128<<24-l%32;var k=b.floor(d/
4294967296);c[(l+64>>>9<<4)+15]=(k<<8|k>>>24)&16711935|(k<<24|k>>>8)&4278255360;c[(l+64>>>9<<4)+14]=(d<<8|d>>>24)&16711935|(d<<24|d>>>8)&4278255360;a.sigBytes=4*(c.length+1);this._process();a=this._hash;c=a.words;for(d=0;4>d;d++)l=c[d],c[d]=(l<<8|l>>>24)&16711935|(l<<24|l>>>8)&4278255360;return a},clone:function(){var a=u.clone.call(this);a._hash=this._hash.clone();return a}});p.MD5=u._createHelper(r);p.HmacMD5=u._createHmacHelper(r)})(Math);
(function(){var b=CryptoJS,k=b.enc.Utf8;b.algo.HMAC=b.lib.Base.extend({init:function(a,b){a=this._hasher=new a.init;"string"==typeof b&&(b=k.parse(b));var m=a.blockSize,p=4*m;b.sigBytes>p&&(b=a.finalize(b));b.clamp();for(var r=this._oKey=b.clone(),v=this._iKey=b.clone(),u=r.words,c=v.words,t=0;t<m;t++)u[t]^=1549556828,c[t]^=909522486;r.sigBytes=v.sigBytes=p;this.reset()},reset:function(){var a=this._hasher;a.reset();a.update(this._iKey)},update:function(a){this._hasher.update(a);return this},finalize:function(a){var b=
this._hasher;a=b.finalize(a);b.reset();return b.finalize(this._oKey.clone().concat(a))}})})();function uuid(){var b=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(k){var a=(b+16*Math.random())%16|0;return b=Math.floor(b/16),("x"===k?a:3&a|8).toString(16)})}
function toBase64(b){var k=b.words,a=b.sigBytes;b.clamp();b=[];for(var l=0;l<a;l+=3)for(var m=(k[l>>>2]>>>24-l%4*8&255)<<16|(k[l+1>>>2]>>>24-(l+1)%4*8&255)<<8|k[l+2>>>2]>>>24-(l+2)%4*8&255,p=0;4>p&&l+.75*p<a;p++)b.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m>>>6*(3-p)&63));for(;b.length%4;)b.push("=");return b.join("")}
function buildAuthData(b){var k=(new Date).getTime()-19555,a=uuid();b=CryptoJS.HmacMD5(a+"\n"+b+"\n"+k,"v1.6.5_956d74858f");return{header:"Authorization:"+("PPG "+a+":"+toBase64(b))+Const.NL+"Timestamp:"+k,deviceId:a}}function isN2MT(b,k){return-1==="enhi|enpt|hien|pten".indexOf(b+k)}
SupportedLanguages=[-1,"auto",-1,-1,-1,-1,-1,-1,-1,-1,-1,"zh-CN","zh-TW",-1,-1,-1,-1,"en",-1,-1,-1,"fr",-1,"de",-1,-1,-1,"hi",-1,-1,"id","it",-1,"ja",-1,"ko",-1,-1,-1,-1,-1,-1,-1,-1,"pt",-1,"ru",-1,-1,-1,"es",-1,-1,"th",-1,-1,-1,"vi",-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1];
function serviceDetectLanguageRequest(b){b=limitSource(b);b="query="+encodePostParam(b);var k=serviceHost()+"/apis/langs/dect",k=postHeader()+Const.NL+buildAuthData(k).header;return new RequestData(HttpMethod.POST,"/apis/langs/dect",b,k)}function serviceDetectLanguageResponse(b){return(b=parseJSON(b))&&b.langCode?languageFromCode(b.langCode):UNKNOWN_LANGUAGE}
function serviceTranslateRequest(b,k,a){b=prepareSource(b);b=limitSource(b);k=codeFromLanguage(k);a=codeFromLanguage(a);-1<"pt|hi".indexOf(k)&&(k=codeFromLanguage(ENGLISH_LANGUAGE));-1<"pt|hi".indexOf(a)&&(a=codeFromLanguage(ENGLISH_LANGUAGE));var l=isN2MT(k,a)?"n2mt":"nsmt",l=format("/apis/{0}/translate",l),m=serviceHost()+l,m=buildAuthData(m);b="deviceId="+m.deviceId+"&source="+k+"&target="+a+"&text="+encodePostParam(b);k=postHeader()+Const.NL+m.header;return new RequestData(HttpMethod.POST,l,b,
k)}function serviceTranslateResponse(b,k,a,l){k=(b=parseJSON(k))&&b.translatedText?b.translatedText:"";b.srcLangType&&(a=languageFromCode(b.srcLangType));b.tarLangType&&(l=languageFromCode(b.tarLangType));return new ResponseData(k,a,l)};
